# =============================================================================================================
#
#  WARNING: This file runs the Docker environment configurator and should not be deleted, moved, or edited.
#
# =============================================================================================================

services:
  magma:
    image: sandftae/magma:1.0
    container_name: environment_builder
    networks:
      - environment_builder_network
    build:
      context: magma
      dockerfile: Dockerfile
    environment:
      - HOST_UID=${HOST_UID:-1000}
      - HOST_GID=${HOST_GID:-1000}
    restart: on-failure:5
    volumes:
      - .:/var/www/src/port-doc:delegated
      - ../:/var/www/src/port-make:delegated
      - ../log/devstack:/app/log:delegated

networks:
  environment_builder_network:
    name: environment_builder_network
    driver: bridge

volumes:
  magma:
    driver: local
