---
name: Shell Scripts Quality

on:
  push:
    branches: [main, development]
  pull_request:
    branches: [main, development]

jobs:
  shellcheck:
    name: Bash Linter (ShellCheck)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          scandir: "env/bash"
        env:
          SHELLCHECK_OPTS: "-s bash"
